In [1]:
import numpy as np
import pickle 
import matplotlib.pyplot as plt

import data_manager as dm

In [16]:
def find_meals_proximity(mp, res):
    distance = 60*16 # 60 seconds    
    bites = mp[res[:, 1]==1, 0]
    #print(bites*0.0625)
    
    clusters = []
    c = [bites[0]]
    for i in range(1, len(bites)):
        if bites[i] - bites[i-1]<=distance:
            c.append(bites[i])
        else:            
            clusters.append(c)
            c = [bites[i]]               
    clusters.append(c)
    
    #res = []    
    #count = len(clusters)
    #i = 0
    #while i <count:
    #    if len(clusters[i]>=4):
            
            
        
    
    if len(clusters) ==0:
        return []
        
    meals = np.zeros((len(clusters), 3))
    for i in range(len(clusters)):        
        meals[i, 0] = clusters[i][0]
        meals[i, 1] = clusters[i][-1]
        meals[i, 2] = len(clusters[i])        
    return meals


In [17]:
def evaluate_result(gt_meals, res_meals):
    print("Ground Truth:")
    a = np.copy(gt_meals)
    a[:, :2] = a[:, :2]*0.0625
    a = a.astype(int)    
    print(a)    
    
    print("Result:")
    if len(res_meals) == 0:
        print(res_meals)
    else:
        a = np.copy(res_meals)
        a[:, :2] = a[:, :2]*0.0625
        a = a.astype(int)
        print(a)    

In [18]:
data = dm.get_data_steven_free()
path = dm.get_root_path()+"\\len_48_48_xth_30_smooth_800\\"
with open(path+"mps.pkl", "rb") as file:
    mps = pickle.load(file)
    
with open(path+"results\\res_all.pkl", "rb") as file:
    res_all = pickle.load(file)

In [19]:
for subject in range(11):    
    for sess in range(len(res_all[subject]["free"])):        
        print("\nSubject {}, Session {}>>".format(subject, sess))
        res = res_all[subject]["free"][sess]
        mp = mps[3][subject][sess]
        #print(len(data[subject+2][sess][1]))
        annot = data[subject][sess][1]
        
        mp_count = len(mp)
        annot_count = len(annot)
        res_count = len(res)        
        
        print("mp_count, res_count: {}, {}".format(mp_count, res_count))
        print("annot_count: {}".format(annot_count))        
        
        res_meals = find_meals_proximity(mp, res)
        #print(annot*0.0625)
        evaluate_result(annot, res_meals)
        
        flag = True
        if flag:
            continue
        
        fig = plt.figure(figsize=(14,10))
        subplot = fig.add_subplot(111)        
        subplot.scatter(mp[:, 0], res[:, 1], marker=".")
        #subplot.plot(d[:, 2], label='Y')
        #subplot.plot(d[:, 3], label='Z')
        #subplot.legend()
        
        
        for i in range(annot_count):            
            ix1 = annot[i, 0]
            ix2 = annot[i, 1]
            meal_type = annot[i, 2]
            
            subplot.plot([ix1, ix1], [-5, 5], '--', c = 'b')
            subplot.plot([ix2, ix2], [-5, 5], c = 'g')
        
        #plt.show()
        plt.savefig("C:\\ASM\\DevData\\eating\\python\\figs2\\"+str(subject)+"_"+str(sess)+".png")
        


Subject 0, Session 0>>
mp_count, res_count: 1253, 1253
annot_count: 3
Ground Truth:
[[  805  1176     1]
 [ 4826  4885     3]
 [18411 20145     1]]
Result:
[[  585   585     1]
 [  770   849     4]
 [  914  1019     3]
 [ 1117  1166     2]
 [ 1846  1846     1]
 [ 3184  3184     1]
 [ 3527  3527     1]
 [ 4385  4385     1]
 [ 4845  4845     1]
 [ 9523  9523     1]
 [12209 12209     1]
 [14294 14294     1]
 [14401 14401     1]
 [16481 16481     1]
 [18464 18516     2]
 [18654 18654     1]
 [18758 18810     3]
 [18876 18901     3]
 [19000 19047     2]
 [19142 19183     2]
 [19283 19430     8]
 [19617 19617     1]
 [19765 19881     9]
 [19941 19941     1]
 [20006 20035     4]
 [20798 20814     2]
 [21065 21065     1]
 [24759 24759     1]
 [25582 25582     1]
 [25942 25942     1]
 [26112 26112     1]
 [26479 26479     1]
 [26715 26715     1]
 [26843 26843     1]
 [26970 26970     1]
 [27522 27522     1]
 [28140 28140     1]
 [28490 28490     1]
 [28703 28703     1]
 [29332 29332     1]
 [3