In [1]:
import numpy as np
#import tensorflow as tf

In [2]:
a = np.random.rand(10,5)
print(a)

[[0.3830381  0.87735363 0.80836663 0.92949469 0.69264118]
 [0.22141673 0.12729956 0.57325402 0.72382772 0.0517319 ]
 [0.52235825 0.29855988 0.05307358 0.87681731 0.07098557]
 [0.47869404 0.82618371 0.05046751 0.24671334 0.36361086]
 [0.26699601 0.38896347 0.52481552 0.90551997 0.40340016]
 [0.34732036 0.37472759 0.7858813  0.28553552 0.74292156]
 [0.66234725 0.07253036 0.54711193 0.66828219 0.86053619]
 [0.82112446 0.55989794 0.20494013 0.04388078 0.57665858]
 [0.90181804 0.25591365 0.16944335 0.50955563 0.11505655]
 [0.27351992 0.25753336 0.5166661  0.77696688 0.28775301]]


In [3]:
b = a[:5]

In [4]:
print(b)

[[0.3830381  0.87735363 0.80836663 0.92949469 0.69264118]
 [0.22141673 0.12729956 0.57325402 0.72382772 0.0517319 ]
 [0.52235825 0.29855988 0.05307358 0.87681731 0.07098557]
 [0.47869404 0.82618371 0.05046751 0.24671334 0.36361086]
 [0.26699601 0.38896347 0.52481552 0.90551997 0.40340016]]


In [7]:
a = tf.multiply(4, 3)
print(a)

Tensor("Mul:0", shape=(), dtype=int32)


In [16]:
a, b = (2, 4)

In [17]:
print(a, b)

2 4


In [1]:
a = lambda x: x+2

In [2]:
print(a(10))

12
