In [2]:
import numpy as np
#import tensorflow as tf

In [4]:
a = np.argwhere(np.arange(10)>5)
print(a)

[[6]
 [7]
 [8]
 [9]]


In [40]:
b = np.random.rand(5,)
print(b)

[0.15272375 0.89891267 0.65318246 0.04946295 0.31661881]


In [41]:
print(a+b)

[[0.40654    1.69427445 1.30110578 0.58908805 0.65566792]
 [1.00069495 1.15024223 0.80892899 0.31678768 1.06531103]
 [0.20838291 1.48269965 1.2946808  0.76307493 0.32911865]
 [0.4200074  1.40113231 1.19183566 0.37342605 0.35959785]
 [0.5498287  1.65540172 0.89823495 0.17873466 0.36156772]]


In [16]:
a, b = (2, 4)

In [17]:
print(a, b)

2 4


In [1]:
a = lambda x: x+2

In [2]:
print(a(10))

12


In [42]:
a = np.array([5, 7, 90])
np.clip(a, 0, 10)

array([ 5,  7, 10])

In [43]:
print(a)

[ 5  7 90]


In [44]:
-a


array([ -5,  -7, -90])