In [87]:
import numpy as np
import pickle
import matplotlib.pyplot as plt
%matplotlib inline

In [88]:
left = 4*16
right = 4*16

In [89]:
def get_data(name):
    path = "C:\\ASM\\DevData\\eating\\python\\"+name+".pkl"
    with open(path, "rb") as file:
        data = pickle.load(file)        
    return data    

In [90]:
def get_segments_session(d, mp):
    mp_count = len(mp)
    #print(mp_count, ", ", len(d))
    #print(mp[mp[:, -1]==1, :])
    y = mp[:, -1]
    x = np.zeros((mp_count, left+right, 3))
    
    for i in range(mp_count):
        ix = mp[i, 0]
        x[i, :, :] = d[ix-left:ix+right, 1:]        
    
    res = {"x":x, "y":y}
    return res        

def get_segments(data, mp):
    subject_count = len(data)
    segments = []
    for subject in range(subject_count):
        subject_data = data[subject]
        subject_mp = mp[subject]
        
        subject_segs = []
        sess_count = len(subject_data)        
        for sess in range(sess_count):
            print("Subject ", subject, ", Session ", sess)
            sess_data = subject_data[sess]        
            sess_mp = subject_mp[sess]
            accel = sess_data[0]
            segs = get_segments_session(accel, sess_mp)
            subject_segs.append(segs)
            
        segments.append(subject_segs)
        
    return segments
    

In [91]:
mps = get_data("selected_min_points")
ds_names = ["uva_lab_data", "steven_lab_data", "uva_free_data", "steven_free_data"]

segments = []
for i in range(4):
    print("Data set: ", ds_names[i])
    ds = get_data(ds_names[i])    
    mp = mps[i]
    segs = get_segments(ds, mp)
    segments.append(segs)

with open("C:\\ASM\\DevData\\eating\\python\\segments.pkl", "wb") as file:
    pickle.dump(segments, file)


Data set:  uva_lab_data
Subject  0 , Session  0
Subject  1 , Session  0
Subject  2 , Session  0
Subject  3 , Session  0
Subject  4 , Session  0
Subject  5 , Session  0
Subject  6 , Session  0
Subject  7 , Session  0
Subject  8 , Session  0
Subject  9 , Session  0
Subject  10 , Session  0
Subject  11 , Session  0
Subject  12 , Session  0
Subject  13 , Session  0
Subject  14 , Session  0
Subject  15 , Session  0
Subject  16 , Session  0
Subject  17 , Session  0
Subject  18 , Session  0
Subject  19 , Session  0
Subject  20 , Session  0
Subject  21 , Session  0
Subject  22 , Session  0
Subject  23 , Session  0
Subject  24 , Session  0
Subject  25 , Session  0
Subject  26 , Session  0
Subject  27 , Session  0
Subject  28 , Session  0
Subject  29 , Session  0
Subject  30 , Session  0
Subject  31 , Session  0
Subject  32 , Session  0
Subject  33 , Session  0
Subject  34 , Session  0
Data set:  steven_lab_data
Subject  0 , Session  0
Subject  1 , Session  0
Subject  2 , Session  0
Subject  2 ,

In [92]:
x = segments[1][0][0]["x"][5, :, :]
print(x)


[[  4.67368012  -2.39287773   6.79861015]
 [  4.87423393  -1.70789245   6.8404652 ]
 [  4.98460141  -0.98142954   7.08965961]
 [  5.1286626   -0.23745085   7.18872518]
 [  5.2776087    0.15957211   7.32683492]
 [  5.40235875   0.44224774   7.5952396 ]
 [  5.49991383   0.74904875   7.94449589]
 [  5.48487706   1.03686066   8.23516221]
 [  5.30025376   1.31697931   8.36909744]
 [  5.1028308    1.64073653   8.3972034 ]
 [  4.9276856    1.91171621   8.35247454]
 [  4.73620983   2.26503092   8.30171156]
 [  4.52803942   2.40105993   8.39616858]
 [  4.32920461   2.49013666   8.49364837]
 [  4.1460633    2.54688439   8.62768543]
 [  4.02176155   2.59537279   8.66148408]
 [  3.92806002   2.78503192   8.58235514]
 [  3.75677849   3.1330223    8.58459096]
 [  3.45012562   3.40082662   8.79534518]
 [  3.07195901   3.55063322   9.08535062]
 [  2.53190302   3.69016507   9.12434101]
 [  1.87379478   3.84439569   9.03339712]
 [  1.16018939   4.10209585   8.83237506]
 [  0.39171258   4.17066101   8.61

In [93]:
segs = get_data('segments')
for ds in range(4):
    pcount = 0
    ncount = 0
    total  = 0
    for subj in range(len(segs[ds])):
        for sess in range(len(segs[ds][subj])):
            y = segs[ds][subj][sess]["y"]
            pcount += sum(y==1)
            ncount += sum(y==0)
            total += len(y)
    print("Dataset {} >> pcount:{}, ncount:{}, total:{}".format(ds, pcount, ncount, total))
            
        
    

Dataset 0 >> pcount:2106, ncount:1505, total:3611
Dataset 1 >> pcount:1122, ncount:6897, total:8019
Dataset 2 >> pcount:0, ncount:2521, total:2521
Dataset 3 >> pcount:6213, ncount:28227, total:34440
