In [14]:
import numpy as np
import pickle
import matplotlib.pyplot as plt

In [49]:
folder = "C:\\ASM\\DevData\\eating\\python\\";

with open(folder+"steven_free_results0.pkl", "rb") as handle:
    res0 = pickle.load(handle)

with open(folder+"steven_free_results1.pkl", "rb") as handle:
    res1 = pickle.load(handle)

with open(folder+"steven_free_results2.pkl", "rb") as handle:
    res2 = pickle.load(handle)

with open(folder+"steven_free_results_left.pkl", "rb") as handle:
    res_left = pickle.load(handle)
    
with open(folder+"steven_free_meals.pkl", "rb") as handle:
    meals = pickle.load(handle)


In [29]:
with open(folder+"steven_free_data.pkl", "rb") as handle:
    data = pickle.load(handle)

In [16]:
%matplotlib inline

In [ ]:
res = res2;
subject_count = len(res)

for subject in range(subject_count):
    sess_count = len(res[subject])
    for sess in range(sess_count):
        d = res[subject][sess]        
        dl = res_left[subject][sess]    
        m = meals[subject][sess]
        
        fig = plt.figure(figsize=(12,10))
        subplot = fig.add_subplot(111)        
        subplot.scatter(d[:, 1]/60, d[:, -1], marker='.', c = 'b')
        subplot.scatter(d[:, 1]/60, d[:, -2], marker='x', c = 'r')
        subplot.scatter(d[:, 1]/60, d[:, -3], marker='+', c = 'g')
        subplot.scatter(dl[:, 1]/60, dl[:, -3], marker='.', c = 'k')
        
        
        r = len(m)        
        if m.ndim ==1:
            r = 1;
            
        for i in range(r):
            if(m.ndim>1):
                ix1 = m[i, 0]
                ix2 = m[i, 1]
                meal_type = m[i, 2]
            else:
                ix1 = m[0]
                ix2 = m[1]
                meal_type = m[2]
                
            t1 = data[subject][sess][ix1, 0]/60
            t2 = data[subject][sess][ix2, 0]/60
            print("Meal ", (i+1), ": ", meal_type, ", ", t1,"-",t2, "> ", (t2-t1))
            
            subplot.plot([t1, t1], [-10, 10], c = 'b')
            subplot.plot([t2, t2], [-10, 10], c = 'g')
            
        
        
        plt.title("Subject:"+str(subject)+", Session: "+str(sess)+", Meal Count: "+str(r))
        plt.show()
        
        

In [56]:
res = res2;
subject_count = len(res)

for subject in range(subject_count):
    sess_count = len(res[subject])
    for sess in range(sess_count):
        print("Subject:"+str(subject)+", Session: "+str(sess))
        b = res[subject][sess]        
        bl = res_left[subject][sess]    
        m = meals[subject][sess]
        d = data[subject][sess];
        
        if m.ndim>1:
            m = m[m[:, -1]<=2, :]
        else:
            m = m.reshape((1,-1))
            
        print(m)
        
        
        

Subject:0, Session: 0
[[  2.85280000e+04   3.38380000e+04   1.00000000e+00]
 [  3.51371000e+05   3.78398000e+05   1.00000000e+00]]
Subject:0, Session: 1
[[  3.01580000e+04   3.99260000e+04   1.00000000e+00]
 [  2.80227000e+05   2.90046000e+05   1.00000000e+00]]
Subject:1, Session: 0
[[  5.56500000e+03   1.88930000e+04   1.00000000e+00]
 [  1.50458000e+05   1.76937000e+05   1.00000000e+00]
 [  3.66618000e+05   4.14396000e+05   1.00000000e+00]
 [  4.32031000e+05   4.32182000e+05   2.00000000e+00]
 [  5.05616000e+05   5.06937000e+05   2.00000000e+00]]
Subject:1, Session: 1
[[  1.56200000e+03   1.17040000e+04   1.00000000e+00]
 [  1.92605000e+05   2.27777000e+05   1.00000000e+00]
 [  3.20760000e+05   3.26568000e+05   2.00000000e+00]
 [  3.42204000e+05   3.46952000e+05   2.00000000e+00]
 [  3.66325000e+05   3.67526000e+05   2.00000000e+00]
 [  4.58883000e+05   4.73677000e+05   1.00000000e+00]]
Subject:2, Session: 0
[[  1.78382000e+05   1.89102000e+05   1.00000000e+00]
 [  1.93146000e+05   2